package com.mycompany.dailyexpenses;

import com.mycompany.dailyexpenses.constants.Constants;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Registration extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private final String INSERT_USER_SQL = "INSERT INTO userlogintbl"
            + "  (username, budget, pass) VALUES "
            + " (?,?,?);";
    private final String UPDATE_USER_SQL = "UPDATE userlogintbl "
            + "SET budget=?, pass=? "
            + "WHERE username = ?";

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpHeader = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jBtnSignUp = new javax.swing.JButton();
        buttonLogIn = new javax.swing.JButton();
        textUserName = new javax.swing.JTextField();
        textBudget = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        jBtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signUpHeader.setText("Login/Signup");

        labelUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUserName.setText("Username");

        labelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAddress.setText("Budget");

        labelPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPassword.setText("Password");

        jBtnSignUp.setText("Sign up");
        jBtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignUpActionPerformed(evt);
            }
        });

        buttonLogIn.setText("Login");
        buttonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogInActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(signUpHeader)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserName)
                            .addComponent(labelAddress)
                            .addComponent(labelPassword))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(textBudget)
                            .addComponent(textUserName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSignUp)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLogIn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jBtnUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(signUpHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUserName)
                    .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(textBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSignUp)
                    .addComponent(buttonLogIn))
                .addGap(18, 18, 18)
                .addComponent(jBtnUpdate)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignUpActionPerformed
        insert();
    }//GEN-LAST:event_jBtnSignUpActionPerformed

    private void buttonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogInActionPerformed
        openLoginFrame();
    }//GEN-LAST:event_buttonLogInActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        update();
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogIn;
    private javax.swing.JButton jBtnSignUp;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel signUpHeader;
    private javax.swing.JTextField textBudget;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables

    public void insert() {
        String username = textUserName.getText().trim();
        char[] pass = textPassword.getPassword();
        String password = new String(pass);
        try {
            double budget = Double.parseDouble(textBudget.getText().trim());
            try {
                Class.forName("org.postgresql.Driver");
                conn = DriverManager.getConnection(Constants.url, Constants.user, Constants.password);
                ps = conn.prepareStatement(INSERT_USER_SQL);
                ps.setString(1, username);
                ps.setDouble(2, budget);
                ps.setString(3, password);
                ps.executeUpdate();
                ps.close();
                conn.close();
                JOptionPane.showMessageDialog(jBtnSignUp, "Data Saved Successfully");
                clear();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnSignUp, "Enter a valid budget");
        }
    }

    public void clear() {
        textUserName.setText("");
        textBudget.setText("");
        textPassword.setText("");
    }

    private void openLoginFrame() {
        setVisible(false);
        new Login().setVisible(true);
    }

    private void update() {
        String username = textUserName.getText().trim();
        char[] pass = textPassword.getPassword();
        String password = new String(pass);
        try {
            double budget = Double.parseDouble(textBudget.getText().trim());
            try {
                Class.forName("org.postgresql.Driver");
                conn = DriverManager.getConnection(Constants.url, Constants.user, Constants.password);
                ps = conn.prepareStatement(UPDATE_USER_SQL);
                ps.setDouble(1, budget);
                ps.setString(2, password);
                ps.setString(3, username);
                ps.executeUpdate();
                ps.close();
                conn.close();
                JOptionPane.showMessageDialog(jBtnUpdate, "Data Saved");
                clear();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnUpdate, "Enter a budget");
        }
    }

}
